import { mkdirSync, rmSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import {
    colors,
    interpolate,
    LAST_MODIFIED,
    localePath,
    locales,
    routePath,
    SITE_URL
} from './site-data.mjs';

const GENERATED_MARKER = '<!-- Generated by scripts/generate-pages.mjs. Do not edit directly. -->';

const escapeHtml = (value) => String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');

const absoluteUrl = (path) => `${SITE_URL}${path}`;

const outputPath = (locale, color) => {
    const route = routePath(locale, color);
    return route === '/' ? 'index.html' : join(route.slice(1), 'index.html');
};

const format = (template, colorName) => interpolate(template, { color: colorName });

const pageCopy = (locale, color) => {
    if (!color) {
        return {
            title: locale.homeTitle,
            description: locale.homeDescription,
            heading: locale.homeHeading,
            lead: locale.homeLead
        };
    }

    const colorName = locale.colors[color.slug];
    const sentenceColorName = locale.code === 'en' ? colorName.toLowerCase() : colorName;
    return {
        title: format(locale.colorTitle, colorName),
        description: format(locale.colorDescription, sentenceColorName),
        heading: format(locale.colorHeading, sentenceColorName),
        lead: format(locale.colorLead, sentenceColorName)
    };
};

const languageAlternates = (color) => [
    ...locales.map((locale) => `    <link rel="alternate" hreflang="${locale.code}" href="${absoluteUrl(routePath(locale, color))}">`),
    `    <link rel="alternate" hreflang="x-default" href="${absoluteUrl(routePath(locales[0], color))}">`
].join('\n');

const colorLinks = (locale, selectedColor) => colors.map((color) => {
    const colorName = locale.colors[color.slug];
    const current = color.slug === selectedColor.slug ? ' aria-current="page"' : '';
    return `                <a class="color-swatch" href="${routePath(locale, color)}" style="--swatch-color: ${color.hex}" title="${escapeHtml(colorName)}" aria-label="${escapeHtml(colorName)}"${current}><span class="visually-hidden">${escapeHtml(colorName)}</span></a>`;
}).join('\n');

const languageOptions = (locale, color) => locales.map((candidate) => {
    const selected = candidate.code === locale.code ? ' selected' : '';
    return `                    <option value="${routePath(candidate, color)}" lang="${candidate.code}"${selected}>${escapeHtml(candidate.name)}</option>`;
}).join('\n');

const translationPayload = (locale) => JSON.stringify({
    exit: locale.exit,
    fullscreen: locale.fullscreen,
    enterFullscreen: locale.enterFullscreen,
    exitFullscreen: locale.exitFullscreen,
    showHelp: locale.showHelp,
    hideHelp: locale.hideHelpLabel,
    resetFeedback: locale.resetFeedback,
    toggleFeedback: locale.toggleFeedback,
    fullscreenUnavailable: locale.fullscreenUnavailable,
    setBrightness: locale.setBrightness,
    presetNames: {
        low: locale.low,
        medium: locale.medium,
        high: locale.high,
        max: locale.max
    }
}).replaceAll('<', '\\u003c');

const schemaPayload = (locale, color, copy, canonical) => JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: copy.heading,
    url: canonical,
    description: copy.description,
    inLanguage: locale.code,
    applicationCategory: 'UtilitiesApplication',
    operatingSystem: 'Any',
    browserRequirements: 'Requires JavaScript and a modern web browser',
    isAccessibleForFree: true,
    offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'USD'
    },
    featureList: color?.slug === 'black'
        ? [locale.fullscreen, locale.color]
        : [locale.brightness, locale.fullscreen, locale.color],
    ...(color ? { keywords: `${locale.colors[color.slug]} screen, ${locale.colors[color.slug]} light` } : {})
}, null, 2).replaceAll('<', '\\u003c');

const renderPage = (locale, requestedColor) => {
    const color = requestedColor || colors[0];
    const copy = pageCopy(locale, requestedColor);
    const path = routePath(locale, requestedColor);
    const canonical = absoluteUrl(path);
    const localHome = routePath(locale);
    const supportsTemperature = color.temperature ? 'true' : 'false';
    const supportsBrightness = color.slug === 'black' ? 'false' : 'true';
    const hiddenOnBlack = color.slug === 'black' ? ' hidden' : '';
    const pageKind = requestedColor ? 'color' : 'home';

    return `<!DOCTYPE html>
<html lang="${locale.code}" dir="${locale.dir}">
${GENERATED_MARKER}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <title>${escapeHtml(copy.title)}</title>
    <meta name="description" content="${escapeHtml(copy.description)}">
    <meta name="author" content="banastas">
    <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1">
    <meta name="theme-color" content="${color.hex}">
    <link rel="canonical" href="${canonical}">
${languageAlternates(requestedColor)}
    <link rel="icon" type="image/png" href="/assets/images/bright.supply.png">
    <link rel="apple-touch-icon" href="/assets/images/bright.supply.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="preload" href="/styles.css" as="style">
    <link rel="stylesheet" href="/styles.css">
    <meta property="og:type" content="website">
    <meta property="og:url" content="${canonical}">
    <meta property="og:title" content="${escapeHtml(copy.title)}">
    <meta property="og:description" content="${escapeHtml(copy.description)}">
    <meta property="og:image" content="${SITE_URL}/assets/images/readme.png">
    <meta property="og:image:alt" content="${escapeHtml(copy.heading)}">
    <meta property="og:site_name" content="bright.supply">
    <meta property="og:locale" content="${locale.code.replace('-', '_')}">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="${escapeHtml(copy.title)}">
    <meta name="twitter:description" content="${escapeHtml(copy.description)}">
    <meta name="twitter:image" content="${SITE_URL}/assets/images/readme.png">
    <meta name="twitter:creator" content="@banastas">
    <script type="application/ld+json">${schemaPayload(locale, requestedColor, copy, canonical)}</script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-DP3EWLQT9L"></script>
    <script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','G-DP3EWLQT9L');</script>
</head>
<body data-page-kind="${pageKind}" data-color-slug="${color.slug}" data-color-value="${color.hex}" data-supports-brightness="${supportsBrightness}" data-supports-temperature="${supportsTemperature}">
    <header class="branding" id="branding" aria-label="bright.supply">
        <h1 class="brand-heading"><a class="brand-link" href="${localHome}"><span class="brand-icon" aria-hidden="true">☀</span><span class="brand-name">bright.supply</span></a>${requestedColor ? `<span class="brand-divider" aria-hidden="true">/</span><span class="page-color-name">${escapeHtml(locale.colors[color.slug])}</span>` : ''}</h1>
    </header>
    <main aria-label="${escapeHtml(locale.selectColor)}">
        <div class="controls-container" role="region" aria-label="${escapeHtml(locale.selectColor)}">
            <div class="color-picker" role="group" aria-label="${escapeHtml(locale.selectColor)}">
                <span class="control-label">${escapeHtml(locale.color)}</span>
                <nav class="color-swatches" aria-label="${escapeHtml(locale.selectColor)}">
${colorLinks(locale, color)}
                </nav>
            </div>
            <div class="slider-container"${hiddenOnBlack}>
                <div class="slider-label-row">
                    <label for="brightness" class="slider-label">${escapeHtml(locale.brightness)}</label>
                    <span class="slider-value" id="brightness-value" aria-live="polite">75%</span>
                </div>
                <input type="range" id="brightness" value="750" min="0" max="1000" class="slider" aria-label="${escapeHtml(locale.brightness)}" aria-valuemin="0" aria-valuemax="1000" aria-valuenow="750">
            </div>
            <div class="preset-buttons" role="group" aria-label="${escapeHtml(locale.presets)}"${hiddenOnBlack}>
                <button id="preset-low" class="preset-btn" aria-label="${escapeHtml(interpolate(locale.setBrightness, { preset: locale.low }))}">${escapeHtml(locale.low)}</button>
                <button id="preset-medium" class="preset-btn" aria-label="${escapeHtml(interpolate(locale.setBrightness, { preset: locale.medium }))}">${escapeHtml(locale.medium)}</button>
                <button id="preset-high" class="preset-btn" aria-label="${escapeHtml(interpolate(locale.setBrightness, { preset: locale.high }))}">${escapeHtml(locale.high)}</button>
                <button id="preset-max" class="preset-btn" aria-label="${escapeHtml(interpolate(locale.setBrightness, { preset: locale.max }))}">${escapeHtml(locale.max)}</button>
            </div>
            <div class="slider-container temperature-container"${color.temperature ? '' : ' hidden'}>
                <label for="temperature" class="slider-label">${escapeHtml(locale.temperature)}</label>
                <div class="temperature-labels"><span class="temp-label temp-cool">${escapeHtml(locale.cool)}</span><span class="temp-label temp-warm">${escapeHtml(locale.warm)}</span></div>
                <input type="range" id="temperature" value="50" min="0" max="100" class="slider temperature-slider" aria-label="${escapeHtml(locale.temperature)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="50">
            </div>
            <div class="utility-row">
                <div class="control-buttons" role="group">
                    <button id="reset-btn" class="control-btn" aria-label="${escapeHtml(locale.resetLabel)}"${hiddenOnBlack}>${escapeHtml(locale.reset)}</button>
                    <button id="fullscreen-btn" class="control-btn" aria-label="${escapeHtml(locale.enterFullscreen)}">${escapeHtml(locale.fullscreen)}</button>
                </div>
                <label class="language-picker">
                    <span class="visually-hidden">${escapeHtml(locale.selectLanguage)}</span>
                    <select id="language-select" aria-label="${escapeHtml(locale.selectLanguage)}">
${languageOptions(locale, requestedColor)}
                    </select>
                </label>
            </div>
        </div>
        <button class="help-toggle" id="help-toggle" aria-label="${escapeHtml(locale.showHelp)}" aria-expanded="false"><span class="help-icon" aria-hidden="true">?</span></button>
        <div class="instructions" id="instructions" aria-live="polite" aria-hidden="true">
            <div class="instructions-header">${escapeHtml(locale.shortcuts)}</div>
            <div class="instructions-grid">
                <div class="shortcut"${hiddenOnBlack}><kbd>←</kbd><kbd>→</kbd><span>${escapeHtml(locale.adjustBrightness)}</span></div>
                <div class="shortcut"><kbd>F</kbd><span>${escapeHtml(locale.fullscreen)}</span></div>
                <div class="shortcut"${hiddenOnBlack}><kbd>R</kbd><span>${escapeHtml(locale.reset)}</span></div>
                <div class="shortcut"><kbd>H</kbd><span>${escapeHtml(locale.hideHelp)}</span></div>
                <div class="shortcut"${hiddenOnBlack}><kbd>Space</kbd><span>${escapeHtml(locale.togglePrevious)}</span></div>
                <div class="shortcut"${hiddenOnBlack}><kbd>1</kbd>–<kbd>4</kbd><span>${escapeHtml(locale.presets)}</span></div>
            </div>
        </div>
        <noscript><p class="noscript-message">JavaScript is required for the interactive controls.</p></noscript>
    </main>
    <script type="application/json" id="app-translations">${translationPayload(locale)}</script>
    <script>if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(error=>console.warn('Service worker registration failed:',error)))}</script>
    <script src="/app.js"></script>
</body>
</html>
`;
};

const generatedDirectories = [
    ...colors.map((color) => color.slug),
    ...locales.filter((locale) => locale.code !== 'en').map(localePath)
];

for (const directory of generatedDirectories) {
    rmSync(directory, { recursive: true, force: true });
}

const pages = [];
for (const locale of locales) {
    pages.push({ locale, color: null });
    for (const color of colors) {
        pages.push({ locale, color });
    }
}

for (const page of pages) {
    const path = outputPath(page.locale, page.color);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, renderPage(page.locale, page.color));
}

const sitemapEntries = pages.map(({ locale, color }) => {
    const path = routePath(locale, color);
    const alternates = locales.map((candidate) => `    <xhtml:link rel="alternate" hreflang="${candidate.code}" href="${absoluteUrl(routePath(candidate, color))}"/>`).join('\n');
    const fallback = `    <xhtml:link rel="alternate" hreflang="x-default" href="${absoluteUrl(routePath(locales[0], color))}"/>`;
    return `  <url>\n    <loc>${absoluteUrl(path)}</loc>\n    <lastmod>${LAST_MODIFIED}</lastmod>\n${alternates}\n${fallback}\n  </url>`;
}).join('\n');

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${sitemapEntries}
</urlset>
`;
writeFileSync('sitemap.xml', sitemap);

process.stdout.write(`Generated ${pages.length} localized pages and sitemap.xml.\n`);
