export const SITE_URL = 'https://bright.supply';
export const LAST_MODIFIED = '2026-08-20';

export const colors = [
    { slug: 'white', hex: '#ffffff', temperature: true },
    { slug: 'black', hex: '#000000' },
    { slug: 'red', hex: '#ff3b30' },
    { slug: 'pink', hex: '#ff2d55' },
    { slug: 'magenta', hex: '#ff00c8' },
    { slug: 'purple', hex: '#af52de' },
    { slug: 'blue', hex: '#0a84ff' },
    { slug: 'cyan', hex: '#64d2ff' },
    { slug: 'teal', hex: '#30b0c7' },
    { slug: 'green', hex: '#30d158' },
    { slug: 'lime', hex: '#b7f34a' },
    { slug: 'yellow', hex: '#ffd60a' },
    { slug: 'amber', hex: '#ff9f0a' },
    { slug: 'orange', hex: '#ff6b00' }
];

const shared = {
    brand: 'bright.supply',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    max: 'Max',
    fullscreen: 'Fullscreen',
    exit: 'Exit',
    reset: 'Reset',
    brightness: 'Brightness',
    color: 'Color',
    temperature: 'Temperature',
    cool: 'Cool',
    warm: 'Warm',
    language: 'Language',
    shortcuts: 'Keyboard shortcuts',
    adjustBrightness: 'Adjust brightness',
    togglePrevious: 'Toggle previous',
    hideHelp: 'Hide help',
    presets: 'Presets',
    showHelp: 'Show keyboard shortcuts',
    hideHelpLabel: 'Hide keyboard shortcuts',
    enterFullscreen: 'Enter fullscreen mode',
    exitFullscreen: 'Exit fullscreen mode',
    resetLabel: 'Reset brightness and temperature',
    setBrightness: 'Set to {preset} brightness',
    resetFeedback: 'Reset to defaults',
    toggleFeedback: 'Toggled brightness',
    fullscreenUnavailable: 'Fullscreen unavailable',
    selectColor: 'Choose a screen color',
    selectLanguage: 'Choose a language',
    pageFeatures: ['Adjustable brightness', 'One-click fullscreen', 'No download or sign-up'],
    homeTitle: 'Free Online Screen Light for Video Calls | bright.supply',
    homeDescription: 'Turn a second monitor into a free adjustable screen light for video calls, photography, streaming, and creative work. Choose white or 13 vivid colors.',
    homeHeading: 'Free online screen light',
    homeLead: 'Turn any monitor, tablet, or phone into an adjustable light. Choose a color, set the brightness, and go fullscreen.',
    colorTitle: '{color} Screen Online | Fullscreen {color} Light | bright.supply',
    colorDescription: 'Open a free adjustable {color} screen online. Set the brightness, go fullscreen, and use any monitor, tablet, or phone to cast {color} light.',
    colorHeading: 'Free {color} screen online',
    colorLead: 'Use this adjustable {color} screen for video calls, photography, streaming, ambience, display testing, and creative work.'
};

const makeLocale = (config) => ({ ...shared, ...config });

export const locales = [
    makeLocale({
        code: 'en', name: 'English', dir: 'ltr',
        colors: { white: 'White', black: 'Black', red: 'Red', pink: 'Pink', magenta: 'Magenta', purple: 'Purple', blue: 'Blue', cyan: 'Cyan', teal: 'Teal', green: 'Green', lime: 'Lime', yellow: 'Yellow', amber: 'Amber', orange: 'Orange' }
    }),
    makeLocale({
        code: 'de', name: 'Deutsch', dir: 'ltr',
        low: 'Niedrig', medium: 'Mittel', high: 'Hoch', max: 'Max.', fullscreen: 'Vollbild', exit: 'Beenden', reset: 'Zurücksetzen', brightness: 'Helligkeit', color: 'Farbe', temperature: 'Farbtemperatur', cool: 'Kühl', warm: 'Warm', language: 'Sprache', shortcuts: 'Tastenkürzel', adjustBrightness: 'Helligkeit anpassen', togglePrevious: 'Vorherige Helligkeit', hideHelp: 'Hilfe ausblenden', presets: 'Voreinstellungen', showHelp: 'Tastenkürzel anzeigen', hideHelpLabel: 'Tastenkürzel ausblenden', enterFullscreen: 'Vollbildmodus starten', exitFullscreen: 'Vollbildmodus beenden', resetLabel: 'Helligkeit und Farbtemperatur zurücksetzen', setBrightness: 'Helligkeit auf {preset} setzen', resetFeedback: 'Auf Standardwerte zurückgesetzt', toggleFeedback: 'Helligkeit gewechselt', fullscreenUnavailable: 'Vollbild ist nicht verfügbar', selectColor: 'Bildschirmfarbe auswählen', selectLanguage: 'Sprache auswählen', pageFeatures: ['Einstellbare Helligkeit', 'Vollbild mit einem Klick', 'Kein Download oder Konto'], homeTitle: 'Kostenloses Online-Bildschirmlicht für Videoanrufe | bright.supply', homeDescription: 'Verwandle einen zweiten Monitor in ein kostenloses, einstellbares Bildschirmlicht für Videoanrufe, Fotografie, Streaming und kreative Arbeit. Wähle Weiß oder 13 leuchtende Farben.', homeHeading: 'Kostenloses Online-Bildschirmlicht', homeLead: 'Verwandle jeden Monitor, jedes Tablet oder Smartphone in eine einstellbare Lichtquelle. Farbe wählen, Helligkeit einstellen und Vollbild starten.', colorTitle: 'Bildschirm in {color} online | {color} Licht im Vollbild | bright.supply', colorDescription: 'Öffne kostenlos einen einstellbaren Bildschirm in {color}. Stelle die Helligkeit ein und nutze Monitor, Tablet oder Smartphone im Vollbild als farbige Lichtquelle.', colorHeading: 'Kostenloser Bildschirm in {color} online', colorLead: 'Nutze diesen einstellbaren Bildschirm in {color} für Videoanrufe, Fotografie, Streaming, Atmosphäre, Displaytests und kreative Arbeit.', colors: { white: 'Weiß', black: 'Schwarz', red: 'Rot', pink: 'Pink', magenta: 'Magenta', purple: 'Violett', blue: 'Blau', cyan: 'Cyan', teal: 'Türkis', green: 'Grün', lime: 'Limettengrün', yellow: 'Gelb', amber: 'Bernstein', orange: 'Orange' }
    }),
    makeLocale({
        code: 'es', name: 'Español', dir: 'ltr',
        low: 'Baja', medium: 'Media', high: 'Alta', max: 'Máx.', fullscreen: 'Pantalla completa', exit: 'Salir', reset: 'Restablecer', brightness: 'Brillo', color: 'Color', temperature: 'Temperatura', cool: 'Fría', warm: 'Cálida', language: 'Idioma', shortcuts: 'Atajos de teclado', adjustBrightness: 'Ajustar brillo', togglePrevious: 'Alternar anterior', hideHelp: 'Ocultar ayuda', presets: 'Preajustes', showHelp: 'Mostrar atajos de teclado', hideHelpLabel: 'Ocultar atajos de teclado', enterFullscreen: 'Entrar en pantalla completa', exitFullscreen: 'Salir de pantalla completa', resetLabel: 'Restablecer brillo y temperatura', setBrightness: 'Establecer brillo {preset}', resetFeedback: 'Valores predeterminados restaurados', toggleFeedback: 'Brillo alternado', fullscreenUnavailable: 'Pantalla completa no disponible', selectColor: 'Elegir un color de pantalla', selectLanguage: 'Elegir un idioma', pageFeatures: ['Brillo ajustable', 'Pantalla completa con un clic', 'Sin descargas ni registro'], homeTitle: 'Luz de pantalla online gratis para videollamadas | bright.supply', homeDescription: 'Convierte un segundo monitor en una luz de pantalla ajustable y gratis para videollamadas, fotografía, streaming y trabajos creativos. Elige blanco o 13 colores vivos.', homeHeading: 'Luz de pantalla online gratis', homeLead: 'Convierte cualquier monitor, tableta o teléfono en una luz ajustable. Elige un color, ajusta el brillo y usa la pantalla completa.', colorTitle: 'Pantalla {color} online | Luz {color} a pantalla completa | bright.supply', colorDescription: 'Abre gratis una pantalla {color} ajustable. Regula el brillo, usa la pantalla completa y convierte cualquier monitor, tableta o teléfono en una luz {color}.', colorHeading: 'Pantalla {color} online gratis', colorLead: 'Usa esta pantalla {color} ajustable para videollamadas, fotografía, streaming, ambiente, pruebas de pantalla y trabajos creativos.', colors: { white: 'blanca', black: 'negra', red: 'roja', pink: 'rosa', magenta: 'magenta', purple: 'morada', blue: 'azul', cyan: 'cian', teal: 'turquesa', green: 'verde', lime: 'lima', yellow: 'amarilla', amber: 'ámbar', orange: 'naranja' }
    }),
    makeLocale({
        code: 'fr', name: 'Français', dir: 'ltr',
        low: 'Faible', medium: 'Moyenne', high: 'Forte', max: 'Max.', fullscreen: 'Plein écran', exit: 'Quitter', reset: 'Réinitialiser', brightness: 'Luminosité', color: 'Couleur', temperature: 'Température', cool: 'Froide', warm: 'Chaude', language: 'Langue', shortcuts: 'Raccourcis clavier', adjustBrightness: 'Régler la luminosité', togglePrevious: 'Revenir au réglage précédent', hideHelp: 'Masquer l’aide', presets: 'Préréglages', showHelp: 'Afficher les raccourcis clavier', hideHelpLabel: 'Masquer les raccourcis clavier', enterFullscreen: 'Passer en plein écran', exitFullscreen: 'Quitter le plein écran', resetLabel: 'Réinitialiser la luminosité et la température', setBrightness: 'Régler la luminosité sur {preset}', resetFeedback: 'Valeurs par défaut restaurées', toggleFeedback: 'Luminosité alternée', fullscreenUnavailable: 'Plein écran indisponible', selectColor: 'Choisir une couleur d’écran', selectLanguage: 'Choisir une langue', pageFeatures: ['Luminosité réglable', 'Plein écran en un clic', 'Sans téléchargement ni inscription'], homeTitle: 'Éclairage d’écran gratuit en ligne pour les appels vidéo | bright.supply', homeDescription: 'Transformez un second écran en éclairage réglable gratuit pour les appels vidéo, la photo, le streaming et la création. Choisissez le blanc ou 13 couleurs vives.', homeHeading: 'Éclairage d’écran gratuit en ligne', homeLead: 'Transformez un moniteur, une tablette ou un téléphone en lumière réglable. Choisissez une couleur, réglez la luminosité et passez en plein écran.', colorTitle: 'Écran {color} en ligne | Lumière {color} plein écran | bright.supply', colorDescription: 'Ouvrez gratuitement un écran {color} réglable. Ajustez la luminosité, passez en plein écran et utilisez tout appareil comme lumière {color}.', colorHeading: 'Écran {color} gratuit en ligne', colorLead: 'Utilisez cet écran {color} réglable pour les appels vidéo, la photo, le streaming, l’ambiance, les tests d’affichage et la création.', colors: { white: 'blanc', black: 'noir', red: 'rouge', pink: 'rose', magenta: 'magenta', purple: 'violet', blue: 'bleu', cyan: 'cyan', teal: 'turquoise', green: 'vert', lime: 'citron vert', yellow: 'jaune', amber: 'ambre', orange: 'orange' }
    }),
    makeLocale({
        code: 'id', name: 'Bahasa Indonesia', dir: 'ltr',
        low: 'Rendah', medium: 'Sedang', high: 'Tinggi', max: 'Maks.', fullscreen: 'Layar penuh', exit: 'Keluar', reset: 'Atur ulang', brightness: 'Kecerahan', color: 'Warna', temperature: 'Suhu warna', cool: 'Sejuk', warm: 'Hangat', language: 'Bahasa', shortcuts: 'Pintasan keyboard', adjustBrightness: 'Atur kecerahan', togglePrevious: 'Beralih ke sebelumnya', hideHelp: 'Sembunyikan bantuan', presets: 'Preset', showHelp: 'Tampilkan pintasan keyboard', hideHelpLabel: 'Sembunyikan pintasan keyboard', enterFullscreen: 'Masuk layar penuh', exitFullscreen: 'Keluar dari layar penuh', resetLabel: 'Atur ulang kecerahan dan suhu warna', setBrightness: 'Atur kecerahan ke {preset}', resetFeedback: 'Kembali ke pengaturan awal', toggleFeedback: 'Kecerahan dialihkan', fullscreenUnavailable: 'Layar penuh tidak tersedia', selectColor: 'Pilih warna layar', selectLanguage: 'Pilih bahasa', pageFeatures: ['Kecerahan dapat diatur', 'Layar penuh sekali klik', 'Tanpa unduhan atau pendaftaran'], homeTitle: 'Lampu Layar Online Gratis untuk Panggilan Video | bright.supply', homeDescription: 'Ubah monitor kedua menjadi lampu layar gratis yang dapat diatur untuk panggilan video, fotografi, streaming, dan karya kreatif. Pilih putih atau 13 warna cerah.', homeHeading: 'Lampu layar online gratis', homeLead: 'Ubah monitor, tablet, atau ponsel menjadi lampu yang dapat diatur. Pilih warna, atur kecerahan, lalu gunakan layar penuh.', colorTitle: 'Layar {color} Online | Lampu {color} Layar Penuh | bright.supply', colorDescription: 'Buka layar {color} gratis yang dapat diatur. Atur kecerahan, gunakan layar penuh, dan jadikan perangkat apa pun sebagai lampu {color}.', colorHeading: 'Layar {color} online gratis', colorLead: 'Gunakan layar {color} yang dapat diatur ini untuk panggilan video, fotografi, streaming, suasana, pengujian layar, dan karya kreatif.', colors: { white: 'putih', black: 'hitam', red: 'merah', pink: 'merah muda', magenta: 'magenta', purple: 'ungu', blue: 'biru', cyan: 'sian', teal: 'toska', green: 'hijau', lime: 'hijau limau', yellow: 'kuning', amber: 'amber', orange: 'jingga' }
    }),
    makeLocale({
        code: 'it', name: 'Italiano', dir: 'ltr',
        low: 'Bassa', medium: 'Media', high: 'Alta', max: 'Max', fullscreen: 'Schermo intero', exit: 'Esci', reset: 'Ripristina', brightness: 'Luminosità', color: 'Colore', temperature: 'Temperatura', cool: 'Fredda', warm: 'Calda', language: 'Lingua', shortcuts: 'Scorciatoie da tastiera', adjustBrightness: 'Regola luminosità', togglePrevious: 'Alterna precedente', hideHelp: 'Nascondi aiuto', presets: 'Preimpostazioni', showHelp: 'Mostra scorciatoie da tastiera', hideHelpLabel: 'Nascondi scorciatoie da tastiera', enterFullscreen: 'Attiva schermo intero', exitFullscreen: 'Esci da schermo intero', resetLabel: 'Ripristina luminosità e temperatura', setBrightness: 'Imposta luminosità {preset}', resetFeedback: 'Valori predefiniti ripristinati', toggleFeedback: 'Luminosità alternata', fullscreenUnavailable: 'Schermo intero non disponibile', selectColor: 'Scegli un colore dello schermo', selectLanguage: 'Scegli una lingua', pageFeatures: ['Luminosità regolabile', 'Schermo intero con un clic', 'Nessun download o registrazione'], homeTitle: 'Luce dello schermo online gratuita per videochiamate | bright.supply', homeDescription: 'Trasforma un secondo monitor in una luce regolabile gratuita per videochiamate, fotografia, streaming e creatività. Scegli il bianco o 13 colori vivaci.', homeHeading: 'Luce dello schermo online gratuita', homeLead: 'Trasforma qualsiasi monitor, tablet o telefono in una luce regolabile. Scegli un colore, regola la luminosità e attiva lo schermo intero.', colorTitle: 'Schermo {color} online | Luce {color} a schermo intero | bright.supply', colorDescription: 'Apri gratuitamente uno schermo {color} regolabile. Regola la luminosità, attiva lo schermo intero e usa qualsiasi dispositivo come luce {color}.', colorHeading: 'Schermo {color} online gratuito', colorLead: 'Usa questo schermo {color} regolabile per videochiamate, fotografia, streaming, atmosfera, test dello schermo e lavori creativi.', colors: { white: 'bianco', black: 'nero', red: 'rosso', pink: 'rosa', magenta: 'magenta', purple: 'viola', blue: 'blu', cyan: 'ciano', teal: 'verde acqua', green: 'verde', lime: 'lime', yellow: 'giallo', amber: 'ambra', orange: 'arancione' }
    }),
    makeLocale({
        code: 'pl', name: 'Polski', dir: 'ltr',
        low: 'Niska', medium: 'Średnia', high: 'Wysoka', max: 'Maks.', fullscreen: 'Pełny ekran', exit: 'Wyjdź', reset: 'Resetuj', brightness: 'Jasność', color: 'Kolor', temperature: 'Temperatura', cool: 'Chłodna', warm: 'Ciepła', language: 'Język', shortcuts: 'Skróty klawiaturowe', adjustBrightness: 'Dostosuj jasność', togglePrevious: 'Przełącz poprzednią', hideHelp: 'Ukryj pomoc', presets: 'Ustawienia', showHelp: 'Pokaż skróty klawiaturowe', hideHelpLabel: 'Ukryj skróty klawiaturowe', enterFullscreen: 'Włącz pełny ekran', exitFullscreen: 'Wyłącz pełny ekran', resetLabel: 'Zresetuj jasność i temperaturę', setBrightness: 'Ustaw jasność na {preset}', resetFeedback: 'Przywrócono ustawienia domyślne', toggleFeedback: 'Przełączono jasność', fullscreenUnavailable: 'Pełny ekran jest niedostępny', selectColor: 'Wybierz kolor ekranu', selectLanguage: 'Wybierz język', pageFeatures: ['Regulowana jasność', 'Pełny ekran jednym kliknięciem', 'Bez pobierania i rejestracji'], homeTitle: 'Darmowe światło ekranowe online do wideorozmów | bright.supply', homeDescription: 'Zmień drugi monitor w bezpłatne, regulowane światło do wideorozmów, fotografii, streamingu i pracy twórczej. Wybierz biały lub 13 żywych kolorów.', homeHeading: 'Darmowe światło ekranowe online', homeLead: 'Zmień monitor, tablet lub telefon w regulowane światło. Wybierz kolor, ustaw jasność i włącz pełny ekran.', colorTitle: 'Ekran {color} online | Światło {color} na pełnym ekranie | bright.supply', colorDescription: 'Otwórz darmowy, regulowany ekran {color}. Ustaw jasność, włącz pełny ekran i użyj dowolnego urządzenia jako światła {color}.', colorHeading: 'Darmowy ekran {color} online', colorLead: 'Użyj regulowanego ekranu {color} do wideorozmów, fotografii, streamingu, nastroju, testowania wyświetlacza i pracy twórczej.', colors: { white: 'biały', black: 'czarny', red: 'czerwony', pink: 'różowy', magenta: 'magenta', purple: 'fioletowy', blue: 'niebieski', cyan: 'cyjan', teal: 'turkusowy', green: 'zielony', lime: 'limonkowy', yellow: 'żółty', amber: 'bursztynowy', orange: 'pomarańczowy' }
    }),
    makeLocale({
        code: 'pt', name: 'Português', dir: 'ltr',
        low: 'Baixa', medium: 'Média', high: 'Alta', max: 'Máx.', fullscreen: 'Tela cheia', exit: 'Sair', reset: 'Redefinir', brightness: 'Brilho', color: 'Cor', temperature: 'Temperatura', cool: 'Fria', warm: 'Quente', language: 'Idioma', shortcuts: 'Atalhos do teclado', adjustBrightness: 'Ajustar brilho', togglePrevious: 'Alternar anterior', hideHelp: 'Ocultar ajuda', presets: 'Predefinições', showHelp: 'Mostrar atalhos do teclado', hideHelpLabel: 'Ocultar atalhos do teclado', enterFullscreen: 'Entrar em tela cheia', exitFullscreen: 'Sair da tela cheia', resetLabel: 'Redefinir brilho e temperatura', setBrightness: 'Definir brilho como {preset}', resetFeedback: 'Padrões restaurados', toggleFeedback: 'Brilho alternado', fullscreenUnavailable: 'Tela cheia indisponível', selectColor: 'Escolher uma cor de tela', selectLanguage: 'Escolher um idioma', pageFeatures: ['Brilho ajustável', 'Tela cheia com um clique', 'Sem download ou cadastro'], homeTitle: 'Luz de tela online grátis para videochamadas | bright.supply', homeDescription: 'Transforme um segundo monitor em uma luz de tela ajustável e gratuita para videochamadas, fotografia, streaming e criação. Escolha branco ou 13 cores vivas.', homeHeading: 'Luz de tela online grátis', homeLead: 'Transforme qualquer monitor, tablet ou celular em uma luz ajustável. Escolha uma cor, regule o brilho e use a tela cheia.', colorTitle: 'Tela {color} online | Luz {color} em tela cheia | bright.supply', colorDescription: 'Abra grátis uma tela {color} ajustável. Regule o brilho, use a tela cheia e transforme qualquer dispositivo em uma luz {color}.', colorHeading: 'Tela {color} online grátis', colorLead: 'Use esta tela {color} ajustável para videochamadas, fotografia, streaming, ambiente, testes de tela e trabalhos criativos.', colors: { white: 'branca', black: 'preta', red: 'vermelha', pink: 'rosa', magenta: 'magenta', purple: 'roxa', blue: 'azul', cyan: 'ciano', teal: 'verde-azulada', green: 'verde', lime: 'lima', yellow: 'amarela', amber: 'âmbar', orange: 'laranja' }
    }),
    makeLocale({
        code: 'vi', name: 'Tiếng Việt', dir: 'ltr',
        low: 'Thấp', medium: 'Vừa', high: 'Cao', max: 'Tối đa', fullscreen: 'Toàn màn hình', exit: 'Thoát', reset: 'Đặt lại', brightness: 'Độ sáng', color: 'Màu', temperature: 'Nhiệt độ màu', cool: 'Lạnh', warm: 'Ấm', language: 'Ngôn ngữ', shortcuts: 'Phím tắt', adjustBrightness: 'Điều chỉnh độ sáng', togglePrevious: 'Chuyển mức trước', hideHelp: 'Ẩn trợ giúp', presets: 'Mức đặt sẵn', showHelp: 'Hiện phím tắt', hideHelpLabel: 'Ẩn phím tắt', enterFullscreen: 'Bật toàn màn hình', exitFullscreen: 'Thoát toàn màn hình', resetLabel: 'Đặt lại độ sáng và nhiệt độ màu', setBrightness: 'Đặt độ sáng {preset}', resetFeedback: 'Đã khôi phục mặc định', toggleFeedback: 'Đã chuyển độ sáng', fullscreenUnavailable: 'Không thể dùng toàn màn hình', selectColor: 'Chọn màu màn hình', selectLanguage: 'Chọn ngôn ngữ', pageFeatures: ['Điều chỉnh độ sáng', 'Toàn màn hình một chạm', 'Không cần tải xuống hay đăng ký'], homeTitle: 'Đèn màn hình trực tuyến miễn phí cho cuộc gọi video | bright.supply', homeDescription: 'Biến màn hình phụ thành đèn có thể điều chỉnh miễn phí cho cuộc gọi video, chụp ảnh, phát trực tiếp và sáng tạo. Chọn màu trắng hoặc 13 màu rực rỡ.', homeHeading: 'Đèn màn hình trực tuyến miễn phí', homeLead: 'Biến màn hình, máy tính bảng hoặc điện thoại thành nguồn sáng có thể điều chỉnh. Chọn màu, chỉnh độ sáng và bật toàn màn hình.', colorTitle: 'Màn hình {color} trực tuyến | Đèn {color} toàn màn hình | bright.supply', colorDescription: 'Mở miễn phí màn hình {color} có thể điều chỉnh. Chỉnh độ sáng, bật toàn màn hình và dùng mọi thiết bị làm đèn {color}.', colorHeading: 'Màn hình {color} trực tuyến miễn phí', colorLead: 'Dùng màn hình {color} có thể điều chỉnh cho cuộc gọi video, chụp ảnh, phát trực tiếp, tạo không khí, kiểm tra màn hình và sáng tạo.', colors: { white: 'trắng', black: 'đen', red: 'đỏ', pink: 'hồng', magenta: 'đỏ tươi', purple: 'tím', blue: 'xanh dương', cyan: 'lục lam', teal: 'xanh cổ vịt', green: 'xanh lá', lime: 'xanh chanh', yellow: 'vàng', amber: 'hổ phách', orange: 'cam' }
    }),
    makeLocale({
        code: 'tr', name: 'Türkçe', dir: 'ltr',
        low: 'Düşük', medium: 'Orta', high: 'Yüksek', max: 'Maks.', fullscreen: 'Tam ekran', exit: 'Çık', reset: 'Sıfırla', brightness: 'Parlaklık', color: 'Renk', temperature: 'Renk sıcaklığı', cool: 'Soğuk', warm: 'Sıcak', language: 'Dil', shortcuts: 'Klavye kısayolları', adjustBrightness: 'Parlaklığı ayarla', togglePrevious: 'Öncekine geç', hideHelp: 'Yardımı gizle', presets: 'Hazır ayarlar', showHelp: 'Klavye kısayollarını göster', hideHelpLabel: 'Klavye kısayollarını gizle', enterFullscreen: 'Tam ekrana geç', exitFullscreen: 'Tam ekrandan çık', resetLabel: 'Parlaklığı ve renk sıcaklığını sıfırla', setBrightness: 'Parlaklığı {preset} yap', resetFeedback: 'Varsayılanlar geri yüklendi', toggleFeedback: 'Parlaklık değiştirildi', fullscreenUnavailable: 'Tam ekran kullanılamıyor', selectColor: 'Ekran rengi seç', selectLanguage: 'Dil seç', pageFeatures: ['Ayarlanabilir parlaklık', 'Tek tıkla tam ekran', 'İndirme veya kayıt yok'], homeTitle: 'Görüntülü Aramalar için Ücretsiz Çevrimiçi Ekran Işığı | bright.supply', homeDescription: 'İkinci monitörü görüntülü aramalar, fotoğraf, yayın ve yaratıcı işler için ücretsiz ayarlanabilir ekran ışığına dönüştürün. Beyaz veya 13 canlı renk seçin.', homeHeading: 'Ücretsiz çevrimiçi ekran ışığı', homeLead: 'Monitör, tablet veya telefonu ayarlanabilir bir ışığa dönüştürün. Renk seçin, parlaklığı ayarlayın ve tam ekrana geçin.', colorTitle: 'Çevrimiçi {color} Ekran | Tam Ekran {color} Işık | bright.supply', colorDescription: 'Ücretsiz ayarlanabilir {color} ekran açın. Parlaklığı ayarlayın, tam ekrana geçin ve her cihazı {color} ışık olarak kullanın.', colorHeading: 'Ücretsiz çevrimiçi {color} ekran', colorLead: 'Bu ayarlanabilir {color} ekranı görüntülü aramalar, fotoğraf, yayın, ortam ışığı, ekran testi ve yaratıcı işler için kullanın.', colors: { white: 'beyaz', black: 'siyah', red: 'kırmızı', pink: 'pembe', magenta: 'macenta', purple: 'mor', blue: 'mavi', cyan: 'camgöbeği', teal: 'turkuaz', green: 'yeşil', lime: 'limon yeşili', yellow: 'sarı', amber: 'kehribar', orange: 'turuncu' }
    }),
    makeLocale({
        code: 'ru', name: 'Русский', dir: 'ltr',
        low: 'Низкая', medium: 'Средняя', high: 'Высокая', max: 'Макс.', fullscreen: 'На весь экран', exit: 'Выйти', reset: 'Сбросить', brightness: 'Яркость', color: 'Цвет', temperature: 'Температура', cool: 'Холодный', warm: 'Тёплый', language: 'Язык', shortcuts: 'Горячие клавиши', adjustBrightness: 'Изменить яркость', togglePrevious: 'Предыдущее значение', hideHelp: 'Скрыть справку', presets: 'Предустановки', showHelp: 'Показать горячие клавиши', hideHelpLabel: 'Скрыть горячие клавиши', enterFullscreen: 'На весь экран', exitFullscreen: 'Выйти из полноэкранного режима', resetLabel: 'Сбросить яркость и температуру', setBrightness: 'Установить яркость: {preset}', resetFeedback: 'Настройки сброшены', toggleFeedback: 'Яркость переключена', fullscreenUnavailable: 'Полноэкранный режим недоступен', selectColor: 'Выбрать цвет экрана', selectLanguage: 'Выбрать язык', pageFeatures: ['Регулируемая яркость', 'Полный экран одним нажатием', 'Без скачивания и регистрации'], homeTitle: 'Бесплатный экранный свет для видеозвонков | bright.supply', homeDescription: 'Превратите второй монитор в бесплатный регулируемый источник света для видеозвонков, фото, стриминга и творчества. Выберите белый или 13 ярких цветов.', homeHeading: 'Бесплатный экранный свет онлайн', homeLead: 'Превратите монитор, планшет или телефон в регулируемый источник света. Выберите цвет, настройте яркость и включите полный экран.', colorTitle: '{color} экран онлайн | {color} свет на весь экран | bright.supply', colorDescription: 'Откройте бесплатный регулируемый {color} экран. Настройте яркость, включите полный экран и используйте любое устройство как {color} свет.', colorHeading: 'Бесплатный {color} экран онлайн', colorLead: 'Используйте регулируемый {color} экран для видеозвонков, фото, стриминга, атмосферы, проверки дисплея и творчества.', colors: { white: 'белый', black: 'чёрный', red: 'красный', pink: 'розовый', magenta: 'пурпурный', purple: 'фиолетовый', blue: 'синий', cyan: 'голубой', teal: 'бирюзовый', green: 'зелёный', lime: 'лаймовый', yellow: 'жёлтый', amber: 'янтарный', orange: 'оранжевый' }
    }),
    makeLocale({
        code: 'ar', name: 'العربية', dir: 'rtl',
        low: 'منخفض', medium: 'متوسط', high: 'عالٍ', max: 'أقصى', fullscreen: 'ملء الشاشة', exit: 'خروج', reset: 'إعادة ضبط', brightness: 'السطوع', color: 'اللون', temperature: 'حرارة اللون', cool: 'بارد', warm: 'دافئ', language: 'اللغة', shortcuts: 'اختصارات لوحة المفاتيح', adjustBrightness: 'ضبط السطوع', togglePrevious: 'التبديل إلى السابق', hideHelp: 'إخفاء المساعدة', presets: 'إعدادات مسبقة', showHelp: 'إظهار اختصارات لوحة المفاتيح', hideHelpLabel: 'إخفاء اختصارات لوحة المفاتيح', enterFullscreen: 'تشغيل ملء الشاشة', exitFullscreen: 'الخروج من ملء الشاشة', resetLabel: 'إعادة ضبط السطوع وحرارة اللون', setBrightness: 'ضبط السطوع على {preset}', resetFeedback: 'تمت استعادة الإعدادات الافتراضية', toggleFeedback: 'تم تبديل السطوع', fullscreenUnavailable: 'ملء الشاشة غير متاح', selectColor: 'اختر لون الشاشة', selectLanguage: 'اختر اللغة', pageFeatures: ['سطوع قابل للتعديل', 'ملء الشاشة بنقرة واحدة', 'من دون تنزيل أو تسجيل'], homeTitle: 'إضاءة شاشة مجانية لمكالمات الفيديو | bright.supply', homeDescription: 'حوّل شاشة ثانية إلى إضاءة مجانية قابلة للتعديل لمكالمات الفيديو والتصوير والبث والعمل الإبداعي. اختر الأبيض أو 13 لونًا زاهيًا.', homeHeading: 'إضاءة شاشة مجانية عبر الإنترنت', homeLead: 'حوّل أي شاشة أو جهاز لوحي أو هاتف إلى ضوء قابل للتعديل. اختر لونًا واضبط السطوع وشغّل ملء الشاشة.', colorTitle: 'شاشة {color} عبر الإنترنت | ضوء {color} بملء الشاشة | bright.supply', colorDescription: 'افتح شاشة {color} مجانية قابلة للتعديل. اضبط السطوع وشغّل ملء الشاشة واستخدم أي جهاز كضوء {color}.', colorHeading: 'شاشة {color} مجانية عبر الإنترنت', colorLead: 'استخدم هذه الشاشة {color} القابلة للتعديل لمكالمات الفيديو والتصوير والبث والأجواء واختبار الشاشة والعمل الإبداعي.', colors: { white: 'بيضاء', black: 'سوداء', red: 'حمراء', pink: 'وردية', magenta: 'أرجوانية', purple: 'بنفسجية', blue: 'زرقاء', cyan: 'سماوية', teal: 'فيروزية', green: 'خضراء', lime: 'ليمونية', yellow: 'صفراء', amber: 'كهرمانية', orange: 'برتقالية' }
    }),
    makeLocale({
        code: 'hi', name: 'हिन्दी', dir: 'ltr',
        low: 'कम', medium: 'मध्यम', high: 'तेज़', max: 'अधिकतम', fullscreen: 'फ़ुलस्क्रीन', exit: 'बाहर', reset: 'रीसेट', brightness: 'चमक', color: 'रंग', temperature: 'रंग तापमान', cool: 'ठंडा', warm: 'गर्म', language: 'भाषा', shortcuts: 'कीबोर्ड शॉर्टकट', adjustBrightness: 'चमक बदलें', togglePrevious: 'पिछली चमक', hideHelp: 'मदद छिपाएँ', presets: 'प्रीसेट', showHelp: 'कीबोर्ड शॉर्टकट दिखाएँ', hideHelpLabel: 'कीबोर्ड शॉर्टकट छिपाएँ', enterFullscreen: 'फ़ुलस्क्रीन चालू करें', exitFullscreen: 'फ़ुलस्क्रीन से बाहर निकलें', resetLabel: 'चमक और रंग तापमान रीसेट करें', setBrightness: 'चमक {preset} करें', resetFeedback: 'डिफ़ॉल्ट सेटिंग बहाल', toggleFeedback: 'चमक बदली गई', fullscreenUnavailable: 'फ़ुलस्क्रीन उपलब्ध नहीं', selectColor: 'स्क्रीन का रंग चुनें', selectLanguage: 'भाषा चुनें', pageFeatures: ['बदलने योग्य चमक', 'एक क्लिक में फ़ुलस्क्रीन', 'डाउनलोड या साइन-अप नहीं'], homeTitle: 'वीडियो कॉल के लिए मुफ़्त ऑनलाइन स्क्रीन लाइट | bright.supply', homeDescription: 'दूसरे मॉनिटर को वीडियो कॉल, फ़ोटोग्राफ़ी, स्ट्रीमिंग और रचनात्मक काम के लिए मुफ़्त स्क्रीन लाइट बनाएँ। सफ़ेद या 13 चमकीले रंग चुनें।', homeHeading: 'मुफ़्त ऑनलाइन स्क्रीन लाइट', homeLead: 'किसी भी मॉनिटर, टैबलेट या फ़ोन को बदलने योग्य लाइट बनाएँ। रंग चुनें, चमक सेट करें और फ़ुलस्क्रीन करें।', colorTitle: 'ऑनलाइन {color} स्क्रीन | फ़ुलस्क्रीन {color} लाइट | bright.supply', colorDescription: 'मुफ़्त बदलने योग्य {color} स्क्रीन खोलें। चमक सेट करें, फ़ुलस्क्रीन करें और किसी भी डिवाइस को {color} लाइट की तरह इस्तेमाल करें।', colorHeading: 'मुफ़्त ऑनलाइन {color} स्क्रीन', colorLead: 'इस बदलने योग्य {color} स्क्रीन को वीडियो कॉल, फ़ोटोग्राफ़ी, स्ट्रीमिंग, माहौल, डिस्प्ले टेस्ट और रचनात्मक काम के लिए इस्तेमाल करें।', colors: { white: 'सफ़ेद', black: 'काली', red: 'लाल', pink: 'गुलाबी', magenta: 'मैजेंटा', purple: 'बैंगनी', blue: 'नीली', cyan: 'सियान', teal: 'टील', green: 'हरी', lime: 'लाइम', yellow: 'पीली', amber: 'ऐंबर', orange: 'नारंगी' }
    }),
    makeLocale({
        code: 'th', name: 'ไทย', dir: 'ltr',
        low: 'ต่ำ', medium: 'กลาง', high: 'สูง', max: 'สูงสุด', fullscreen: 'เต็มจอ', exit: 'ออก', reset: 'รีเซ็ต', brightness: 'ความสว่าง', color: 'สี', temperature: 'อุณหภูมิสี', cool: 'เย็น', warm: 'อุ่น', language: 'ภาษา', shortcuts: 'แป้นพิมพ์ลัด', adjustBrightness: 'ปรับความสว่าง', togglePrevious: 'สลับค่าก่อนหน้า', hideHelp: 'ซ่อนวิธีใช้', presets: 'ค่าที่ตั้งไว้', showHelp: 'แสดงแป้นพิมพ์ลัด', hideHelpLabel: 'ซ่อนแป้นพิมพ์ลัด', enterFullscreen: 'เปิดเต็มจอ', exitFullscreen: 'ออกจากเต็มจอ', resetLabel: 'รีเซ็ตความสว่างและอุณหภูมิสี', setBrightness: 'ตั้งความสว่างเป็น {preset}', resetFeedback: 'คืนค่าเริ่มต้นแล้ว', toggleFeedback: 'สลับความสว่างแล้ว', fullscreenUnavailable: 'ไม่สามารถใช้เต็มจอ', selectColor: 'เลือกสีหน้าจอ', selectLanguage: 'เลือกภาษา', pageFeatures: ['ปรับความสว่างได้', 'เต็มจอในคลิกเดียว', 'ไม่ต้องดาวน์โหลดหรือสมัคร'], homeTitle: 'ไฟหน้าจอออนไลน์ฟรีสำหรับวิดีโอคอล | bright.supply', homeDescription: 'เปลี่ยนจอที่สองให้เป็นไฟหน้าจอฟรีที่ปรับได้สำหรับวิดีโอคอล ถ่ายภาพ สตรีม และงานสร้างสรรค์ เลือกสีขาวหรือ 13 สีสด', homeHeading: 'ไฟหน้าจอออนไลน์ฟรี', homeLead: 'เปลี่ยนจอ แท็บเล็ต หรือโทรศัพท์ให้เป็นไฟที่ปรับได้ เลือกสี ปรับความสว่าง แล้วเปิดเต็มจอ', colorTitle: 'หน้าจอ{color}ออนไลน์ | ไฟ{color}เต็มจอ | bright.supply', colorDescription: 'เปิดหน้าจอ{color}ฟรีที่ปรับได้ ปรับความสว่าง เปิดเต็มจอ และใช้อุปกรณ์ใดก็ได้เป็นไฟ{color}', colorHeading: 'หน้าจอ{color}ออนไลน์ฟรี', colorLead: 'ใช้หน้าจอ{color}ที่ปรับได้นี้สำหรับวิดีโอคอล ถ่ายภาพ สตรีม สร้างบรรยากาศ ทดสอบจอ และงานสร้างสรรค์', colors: { white: 'สีขาว', black: 'สีดำ', red: 'สีแดง', pink: 'สีชมพู', magenta: 'สีบานเย็น', purple: 'สีม่วง', blue: 'สีน้ำเงิน', cyan: 'สีฟ้า', teal: 'สีเขียวอมฟ้า', green: 'สีเขียว', lime: 'สีเขียวมะนาว', yellow: 'สีเหลือง', amber: 'สีอำพัน', orange: 'สีส้ม' }
    }),
    makeLocale({
        code: 'zh-Hans', path: 'zh-cn', name: '简体中文', dir: 'ltr',
        low: '低', medium: '中', high: '高', max: '最大', fullscreen: '全屏', exit: '退出', reset: '重置', brightness: '亮度', color: '颜色', temperature: '色温', cool: '冷', warm: '暖', language: '语言', shortcuts: '键盘快捷键', adjustBrightness: '调节亮度', togglePrevious: '切换上次亮度', hideHelp: '隐藏帮助', presets: '预设', showHelp: '显示键盘快捷键', hideHelpLabel: '隐藏键盘快捷键', enterFullscreen: '进入全屏', exitFullscreen: '退出全屏', resetLabel: '重置亮度和色温', setBrightness: '设为{preset}亮度', resetFeedback: '已恢复默认设置', toggleFeedback: '已切换亮度', fullscreenUnavailable: '无法使用全屏', selectColor: '选择屏幕颜色', selectLanguage: '选择语言', pageFeatures: ['亮度可调', '一键全屏', '无需下载或注册'], homeTitle: '视频通话免费在线补光屏 | bright.supply', homeDescription: '将第二台显示器变成免费可调的补光屏，适合视频通话、摄影、直播和创意工作。可选白色和 13 种鲜艳颜色。', homeHeading: '免费在线补光屏', homeLead: '将任何显示器、平板电脑或手机变成可调光源。选择颜色、调整亮度并进入全屏。', colorTitle: '在线{color}屏幕 | 全屏{color}灯光 | bright.supply', colorDescription: '免费打开可调{color}屏幕。调整亮度、进入全屏，并将任何显示器、平板电脑或手机用作{color}光源。', colorHeading: '免费在线{color}屏幕', colorLead: '这款可调{color}屏幕适用于视频通话、摄影、直播、氛围照明、屏幕测试和创意工作。', colors: { white: '白色', black: '黑色', red: '红色', pink: '粉色', magenta: '洋红色', purple: '紫色', blue: '蓝色', cyan: '青色', teal: '蓝绿色', green: '绿色', lime: '青柠色', yellow: '黄色', amber: '琥珀色', orange: '橙色' }
    }),
    makeLocale({
        code: 'zh-Hant', path: 'zh-tw', name: '繁體中文', dir: 'ltr',
        low: '低', medium: '中', high: '高', max: '最大', fullscreen: '全螢幕', exit: '離開', reset: '重設', brightness: '亮度', color: '顏色', temperature: '色溫', cool: '冷', warm: '暖', language: '語言', shortcuts: '鍵盤快速鍵', adjustBrightness: '調整亮度', togglePrevious: '切換上次亮度', hideHelp: '隱藏說明', presets: '預設', showHelp: '顯示鍵盤快速鍵', hideHelpLabel: '隱藏鍵盤快速鍵', enterFullscreen: '進入全螢幕', exitFullscreen: '離開全螢幕', resetLabel: '重設亮度與色溫', setBrightness: '設為{preset}亮度', resetFeedback: '已恢復預設值', toggleFeedback: '已切換亮度', fullscreenUnavailable: '無法使用全螢幕', selectColor: '選擇螢幕顏色', selectLanguage: '選擇語言', pageFeatures: ['亮度可調', '一鍵全螢幕', '無需下載或註冊'], homeTitle: '視訊通話免費線上補光螢幕 | bright.supply', homeDescription: '將第二台顯示器變成免費可調的補光螢幕，適合視訊通話、攝影、直播與創意工作。可選白色及 13 種鮮豔顏色。', homeHeading: '免費線上補光螢幕', homeLead: '將任何顯示器、平板或手機變成可調光源。選擇顏色、調整亮度並進入全螢幕。', colorTitle: '線上{color}螢幕 | 全螢幕{color}燈光 | bright.supply', colorDescription: '免費開啟可調{color}螢幕。調整亮度、進入全螢幕，並將任何顯示器、平板或手機用作{color}光源。', colorHeading: '免費線上{color}螢幕', colorLead: '這款可調{color}螢幕適合視訊通話、攝影、直播、氣氛照明、螢幕測試與創意工作。', colors: { white: '白色', black: '黑色', red: '紅色', pink: '粉紅色', magenta: '洋紅色', purple: '紫色', blue: '藍色', cyan: '青色', teal: '藍綠色', green: '綠色', lime: '萊姆色', yellow: '黃色', amber: '琥珀色', orange: '橙色' }
    }),
    makeLocale({
        code: 'ja', name: '日本語', dir: 'ltr',
        low: '低', medium: '中', high: '高', max: '最大', fullscreen: '全画面', exit: '終了', reset: 'リセット', brightness: '明るさ', color: '色', temperature: '色温度', cool: '寒色', warm: '暖色', language: '言語', shortcuts: 'キーボードショートカット', adjustBrightness: '明るさを調整', togglePrevious: '前の明るさに切替', hideHelp: 'ヘルプを隠す', presets: 'プリセット', showHelp: 'キーボードショートカットを表示', hideHelpLabel: 'キーボードショートカットを隠す', enterFullscreen: '全画面にする', exitFullscreen: '全画面を終了', resetLabel: '明るさと色温度をリセット', setBrightness: '明るさを{preset}に設定', resetFeedback: '初期設定に戻しました', toggleFeedback: '明るさを切り替えました', fullscreenUnavailable: '全画面表示を利用できません', selectColor: '画面の色を選択', selectLanguage: '言語を選択', pageFeatures: ['明るさを調整可能', 'ワンクリックで全画面', 'ダウンロードや登録は不要'], homeTitle: 'ビデオ通話用の無料オンライン画面ライト | bright.supply', homeDescription: '2台目のモニターを、ビデオ通話、撮影、配信、クリエイティブ作業用の無料調整式ライトにします。白と13色から選べます。', homeHeading: '無料オンライン画面ライト', homeLead: 'モニター、タブレット、スマートフォンを調整可能なライトにします。色と明るさを選び、全画面で使えます。', colorTitle: 'オンライン{color}画面 | 全画面{color}ライト | bright.supply', colorDescription: '無料の調整可能な{color}画面を開きます。明るさを設定し、全画面でどのデバイスも{color}ライトとして使えます。', colorHeading: '無料オンライン{color}画面', colorLead: 'この調整可能な{color}画面は、ビデオ通話、撮影、配信、雰囲気作り、画面テスト、創作に使えます。', colors: { white: '白色', black: '黒色', red: '赤色', pink: 'ピンク', magenta: 'マゼンタ', purple: '紫色', blue: '青色', cyan: 'シアン', teal: 'ティール', green: '緑色', lime: 'ライム', yellow: '黄色', amber: 'アンバー', orange: 'オレンジ' }
    }),
    makeLocale({
        code: 'ko', name: '한국어', dir: 'ltr',
        low: '낮음', medium: '중간', high: '높음', max: '최대', fullscreen: '전체 화면', exit: '나가기', reset: '초기화', brightness: '밝기', color: '색상', temperature: '색온도', cool: '차갑게', warm: '따뜻하게', language: '언어', shortcuts: '키보드 단축키', adjustBrightness: '밝기 조절', togglePrevious: '이전 밝기 전환', hideHelp: '도움말 숨기기', presets: '프리셋', showHelp: '키보드 단축키 표시', hideHelpLabel: '키보드 단축키 숨기기', enterFullscreen: '전체 화면 시작', exitFullscreen: '전체 화면 종료', resetLabel: '밝기와 색온도 초기화', setBrightness: '밝기를 {preset}(으)로 설정', resetFeedback: '기본값으로 초기화됨', toggleFeedback: '밝기가 전환됨', fullscreenUnavailable: '전체 화면을 사용할 수 없음', selectColor: '화면 색상 선택', selectLanguage: '언어 선택', pageFeatures: ['밝기 조절 가능', '한 번에 전체 화면', '다운로드나 가입 불필요'], homeTitle: '화상 통화용 무료 온라인 화면 조명 | bright.supply', homeDescription: '두 번째 모니터를 화상 통화, 사진, 스트리밍, 창작용 무료 조절식 화면 조명으로 바꿔보세요. 흰색과 13가지 선명한 색상을 제공합니다.', homeHeading: '무료 온라인 화면 조명', homeLead: '모니터, 태블릿, 휴대폰을 조절 가능한 조명으로 바꿔보세요. 색상과 밝기를 선택하고 전체 화면으로 사용하세요.', colorTitle: '온라인 {color} 화면 | 전체 화면 {color} 조명 | bright.supply', colorDescription: '무료 조절식 {color} 화면을 여세요. 밝기를 설정하고 전체 화면에서 모든 기기를 {color} 조명으로 사용할 수 있습니다.', colorHeading: '무료 온라인 {color} 화면', colorLead: '이 조절식 {color} 화면을 화상 통화, 사진, 스트리밍, 분위기 조명, 화면 테스트, 창작에 활용하세요.', colors: { white: '흰색', black: '검은색', red: '빨간색', pink: '분홍색', magenta: '마젠타', purple: '보라색', blue: '파란색', cyan: '시안', teal: '청록색', green: '초록색', lime: '라임색', yellow: '노란색', amber: '호박색', orange: '주황색' }
    })
];

export const localePath = (locale) => locale.code === 'en' ? '' : (locale.path || locale.code.toLowerCase());

export const routePath = (locale, color = null) => {
    const segments = [localePath(locale), color?.slug].filter(Boolean);
    return segments.length === 0 ? '/' : `/${segments.join('/')}/`;
};

export const interpolate = (template, variables) => Object.entries(variables).reduce(
    (value, [key, replacement]) => value.replaceAll(`{${key}}`, replacement),
    template
);
