import { existsSync, readFileSync } from 'fs';
import { dirname, join } from 'path';
import { spawnSync } from 'child_process';
import { colors, LAST_MODIFIED, localePath, locales, routePath, SITE_URL } from './site-data.mjs';

const checks = [];
const record = (name, passed, detail = '') => checks.push({ name, passed, detail });
const readText = (path) => readFileSync(path, 'utf8');
const parseJson = (path) => JSON.parse(readText(path));
const generatedMarker = '<!-- Generated by scripts/generate-pages.mjs. Do not edit directly. -->';

const outputPath = (locale, color) => {
    const route = routePath(locale, color);
    return route === '/' ? 'index.html' : join(route.slice(1), 'index.html');
};

const localPathFromUrl = (value) => {
    if (!value || /^https?:/.test(value)) return null;
    const clean = value.split('?')[0].split('#')[0];
    const normalized = clean.startsWith('/') ? clean.slice(1) : clean;
    return normalized || 'index.html';
};

const getPngSize = (path) => {
    const buffer = readFileSync(path);
    if (buffer.toString('hex', 0, 8) !== '89504e470d0a1a0a') throw new Error(`${path} is not PNG`);
    return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
};

for (const path of ['analytics.js', 'app.js', 'sw.js', 'scripts/test-runtime.mjs', 'scripts/validate.mjs', 'scripts/generate-pages.mjs', 'scripts/site-data.mjs']) {
    const result = spawnSync(process.execPath, ['--check', path], { encoding: 'utf8' });
    record(`${path} syntax`, result.status === 0, result.stderr.trim());
}

let manifest;
let packageJson;
try {
    manifest = parseJson('manifest.json');
    record('manifest.json parses', true);
} catch (error) {
    record('manifest.json parses', false, String(error));
}
try {
    packageJson = parseJson('package.json');
    record('package.json parses', true);
} catch (error) {
    record('package.json parses', false, String(error));
}

record('color slugs are unique', new Set(colors.map(({ slug }) => slug)).size === colors.length);
record('locale codes are unique', new Set(locales.map(({ code }) => code)).size === locales.length);
record('locale paths are unique', new Set(locales.map(localePath)).size === locales.length);
record('English is the default locale', locales[0]?.code === 'en' && localePath(locales[0]) === '');
record('exactly one RTL locale is configured', locales.filter(({ dir }) => dir === 'rtl').length === 1);

for (const locale of locales) {
    record(`${locale.code} has every color name`, colors.every(({ slug }) => Boolean(locale.colors?.[slug])));
    record(`${locale.code} has three page features`, locale.pageFeatures?.length === 3);
}

const pageRecords = [];
for (const locale of locales) {
    pageRecords.push({ locale, color: null });
    for (const color of colors) pageRecords.push({ locale, color });
}

const expectedRoutes = new Set(pageRecords.map(({ locale, color }) => routePath(locale, color)));
record('270 localized routes are configured', pageRecords.length === 270, String(pageRecords.length));
record('all route URLs are unique', expectedRoutes.size === pageRecords.length);

const allTitles = new Set();
const allCanonicals = new Set();
for (const { locale, color } of pageRecords) {
    const path = outputPath(locale, color);
    const route = routePath(locale, color);
    const canonical = `${SITE_URL}${route}`;
    if (!existsSync(path)) {
        record(`page exists: ${route}`, false, path);
        continue;
    }

    const html = readText(path);
    const title = html.match(/<title>([^<]+)<\/title>/)?.[1];
    const description = html.match(/<meta name="description" content="([^"]+)">/)?.[1];
    const canonicalMatch = html.match(/<link rel="canonical" href="([^"]+)">/)?.[1];
    const htmlLanguage = html.match(/<html lang="([^"]+)" dir="([^"]+)">/);
    const h1Count = (html.match(/<h1\b/g) || []).length;
    const alternates = [...html.matchAll(/<link rel="alternate" hreflang="([^"]+)" href="([^"]+)">/g)];
    const colorLinks = [...html.matchAll(/<a class="color-swatch" href="([^"]+)"/g)].map((match) => match[1]);
    const colorSlugs = [...html.matchAll(/<a class="color-swatch"[^>]+data-color-slug="([^"]+)"/g)].map((match) => match[1]);
    const languageValues = [...html.matchAll(/<option value="([^"]+)"/g)].map((match) => match[1]);
    const schemaText = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)?.[1];

    record(`generated marker: ${route}`, html.includes(generatedMarker));
    record(`document language and direction: ${route}`, htmlLanguage?.[1] === locale.code && htmlLanguage?.[2] === locale.dir);
    record(`unique canonical: ${route}`, canonicalMatch === canonical && !allCanonicals.has(canonical));
    const compactScript = ['zh-Hans', 'zh-Hant', 'ja', 'ko'].includes(locale.code);
    const minimumTitleLength = compactScript ? 10 : 20;
    const minimumDescriptionLength = compactScript ? 35 : 70;
    record(`title is useful: ${route}`, Boolean(title && title.length >= minimumTitleLength && title.length <= 90), title || 'missing');
    record(`description is useful: ${route}`, Boolean(description && description.length >= minimumDescriptionLength && description.length <= 220), description || 'missing');
    record(`one H1: ${route}`, h1Count === 1, String(h1Count));
    record(
        `compact color context: ${route}`,
        color
            ? html.includes('class="page-context"') &&
                html.includes('class="page-color-dot"') &&
                !html.includes('class="brand-divider"')
            : !html.includes('class="page-context"')
    );
    record(`utility UI has no promotional hero: ${route}`, !html.includes('class="page-summary"'));
    record(`indexable robots: ${route}`, html.includes('name="robots" content="index, follow'));
    record(`absolute core assets: ${route}`, html.includes('href="/styles.css"') && html.includes('src="/analytics.js"') && html.includes('src="/app.js"') && html.includes('href="/manifest.json"'));
    record(
        `analytics runtime precedes application: ${route}`,
        html.indexOf('src="/analytics.js"') > -1 && html.indexOf('src="/analytics.js"') < html.indexOf('src="/app.js"')
    );
    record(`no duplicated inline Google tag: ${route}`, !html.includes('googletagmanager.com') && !html.includes('G-DP3EWLQT9L'));
    record(`route color data: ${route}`, html.includes(`data-color-slug="${color?.slug || 'white'}"`));
    const isBlackScreen = color?.slug === 'black';
    record(
        `brightness availability matches color: ${route}`,
        html.includes(`data-supports-brightness="${isBlackScreen ? 'false' : 'true'}"`)
    );
    record(
        `black-only controls are truthful: ${route}`,
        isBlackScreen
            ? html.includes('<div class="slider-container" hidden>') &&
                html.includes(`class="preset-buttons" role="group" aria-label="${locale.presets}" hidden`) &&
                html.includes('id="reset-btn" class="control-btn"') &&
                html.includes('id="reset-btn" class="control-btn" aria-label=') &&
                /id="reset-btn"[^>]+ hidden>/.test(html)
            : !html.includes('<div class="slider-container" hidden>')
    );
    record(`all color links: ${route}`, colorLinks.length === colors.length && colorLinks.every((value, index) => value === routePath(locale, colors[index])));
    record(`all color links expose stable analytics slugs: ${route}`, colorSlugs.length === colors.length && colorSlugs.every((value, index) => value === colors[index].slug));
    record(`all language choices: ${route}`, languageValues.length === locales.length && languageValues.every((value, index) => value === routePath(locales[index], color)));
    record(`complete hreflang set: ${route}`, alternates.length === locales.length + 1);

    const alternateMap = new Map(alternates.map((match) => [match[1], match[2]]));
    const hreflangCorrect = locales.every((candidate) => alternateMap.get(candidate.code) === `${SITE_URL}${routePath(candidate, color)}`) &&
        alternateMap.get('x-default') === `${SITE_URL}${routePath(locales[0], color)}`;
    record(`reciprocal hreflang targets: ${route}`, hreflangCorrect);

    try {
        const schema = JSON.parse(schemaText);
        record(`WebApplication schema: ${route}`, schema['@type'] === 'WebApplication' && schema.url === canonical && schema.inLanguage === locale.code);
    } catch (error) {
        record(`WebApplication schema: ${route}`, false, String(error));
    }

    allCanonicals.add(canonical);
    allTitles.add(title);
}
record('every page title is unique', allTitles.size === pageRecords.length, `${allTitles.size}/${pageRecords.length}`);

if (manifest) {
    record('manifest has a stable app identity', manifest.id === '/' && manifest.start_url === '/');
    const imageEntries = [...(manifest.icons || []), ...(manifest.screenshots || [])];
    const assetRefs = [
        ...imageEntries.map(({ src }) => src),
        ...(manifest.shortcuts || []).flatMap(({ icons = [] }) => icons.map(({ src }) => src))
    ];
    for (const ref of assetRefs) {
        const localPath = localPathFromUrl(ref);
        record(`manifest asset exists: ${ref}`, Boolean(localPath && existsSync(localPath)), localPath || ref);
    }
    for (const image of imageEntries) {
        const localPath = localPathFromUrl(image.src);
        if (!localPath || !existsSync(localPath) || !image.sizes) continue;
        const size = getPngSize(localPath);
        record(`manifest size matches: ${image.src}`, image.sizes.split(/\s+/).includes(`${size.width}x${size.height}`), `${size.width}x${size.height}`);
    }
    for (const shortcut of manifest.shortcuts || []) {
        const route = new URL(shortcut.url, SITE_URL).pathname;
        record(`manifest shortcut is generated: ${route}`, expectedRoutes.has(route));
    }
    const iconKeys = (manifest.icons || []).map(({ src, sizes, purpose = '' }) => `${src}|${sizes}|${purpose}`);
    record('manifest icons are unique', new Set(iconKeys).size === iconKeys.length, `${new Set(iconKeys).size}/${iconKeys.length}`);
}

const serviceWorker = readText('sw.js');
const staticFilesMatch = serviceWorker.match(/const STATIC_FILES = \[([\s\S]*?)\];/);
if (staticFilesMatch) {
    const staticFiles = [...staticFilesMatch[1].matchAll(/'([^']+)'/g)].map((match) => match[1]);
    for (const file of staticFiles) {
        const localPath = localPathFromUrl(file);
        record(`service worker cache target exists: ${file}`, Boolean(localPath && existsSync(localPath)), localPath || file);
    }
} else {
    record('service worker static file list is readable', false);
}
record('service worker uses network-first navigation', serviceWorker.includes("request.mode === 'navigate'") && serviceWorker.includes('handleNavigation'));
record(
    'service worker refreshes interface assets online',
    serviceWorker.includes("new Set(['/styles.css', '/analytics.js', '/app.js', '/manifest.json'])") &&
        serviceWorker.includes('NETWORK_FIRST_ASSETS.has(url.pathname)')
);
record('service worker does not precache documentation assets', !serviceWorker.includes("'/assets/images/readme.png'") && !serviceWorker.includes("'/sitemap.xml'"));

const analytics = readText('analytics.js');
const application = readText('app.js');
const expectedAnalyticsEvents = [
    'brightness_change',
    'brightness_toggle',
    'color_select',
    'fullscreen_enter',
    'fullscreen_error',
    'fullscreen_exit',
    'help_toggle',
    'language_select',
    'settings_reset',
    'temperature_change'
];
record('analytics uses the configured GA4 measurement ID', analytics.includes("const MEASUREMENT_ID = 'G-DP3EWLQT9L'"));
record('analytics is production-host gated', analytics.includes("new Set(['bright.supply', 'www.bright.supply'])"));
record('analytics strips query strings from measured URLs', analytics.includes('`${url.origin}${url.pathname}`'));
record('analytics disables Google Signals', analytics.includes('allow_google_signals: false'));
record('analytics disables ad personalization signals', analytics.includes('allow_ad_personalization_signals: false'));
record('application uses the shared analytics adapter', application.includes('window.brightSupplyAnalytics?.track') && !/\bgtag\s*\(/.test(application));
for (const eventName of expectedAnalyticsEvents) {
    record(`analytics event is instrumented: ${eventName}`, application.includes(`'${eventName}'`));
}

const sitemap = readText('sitemap.xml');
const sitemapBlocks = [...sitemap.matchAll(/<url>([\s\S]*?)<\/url>/g)].map((match) => match[1]);
const sitemapLocations = sitemapBlocks.map((block) => block.match(/<loc>([^<]+)<\/loc>/)?.[1]);
record('sitemap has one entry per route', sitemapBlocks.length === pageRecords.length, String(sitemapBlocks.length));
record('sitemap URLs are unique', new Set(sitemapLocations).size === sitemapLocations.length);
record('sitemap has no query URLs', sitemapLocations.every((location) => location && !location.includes('?')));
record('sitemap contains every canonical', pageRecords.every(({ locale, color }) => sitemapLocations.includes(`${SITE_URL}${routePath(locale, color)}`)));

for (const block of sitemapBlocks) {
    const location = block.match(/<loc>([^<]+)<\/loc>/)?.[1] || 'missing';
    const alternates = [...block.matchAll(/<xhtml:link rel="alternate" hreflang="([^"]+)" href="([^"]+)"\/>/g)];
    record(`sitemap lastmod: ${location}`, block.includes(`<lastmod>${LAST_MODIFIED}</lastmod>`));
    record(`sitemap hreflang count: ${location}`, alternates.length === locales.length + 1, String(alternates.length));
}

if (packageJson) {
    record('package is private', packageJson.private === true);
    record('package requires current Node LTS', packageJson.engines?.node === '>=24.0.0', packageJson.engines?.node || 'missing');
    record('build regenerates then validates', packageJson.scripts?.build === 'npm run generate && npm run validate');
}

const robots = readText('robots.txt');
record('robots advertises canonical sitemap', robots.includes(`Sitemap: ${SITE_URL}/sitemap.xml`));
record('robots permits crawling', /User-agent: \*\s+Allow: \//.test(robots));

const failures = checks.filter(({ passed }) => !passed);
if (failures.length) {
    for (const check of failures) {
        const detail = check.detail ? ` - ${check.detail}` : '';
        process.stderr.write(`FAIL ${check.name}${detail}\n`);
    }
    process.stderr.write(`\n${failures.length} of ${checks.length} validation checks failed.\n`);
    process.exit(1);
}
process.stdout.write(`\n${checks.length} validation checks passed across ${pageRecords.length} pages.\n`);
